site_name: AddyScript Wiki
docs_dir: docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight

plugins:
  - search
  - with-pdf:
      output_path: assets/manual.pdf
      cover_title: AddyScript Manual
      cover_subtitle: Developer Documentation
      author: Michel Mbem
      toc_title: Table of Contents
      debug_html: false
      nav:
        - Introduction:
            - Features: features.md
            - Tutorials:
                - Interpreting a script: interpret.md
                - Evaluating expressions: evaluate.md
                - More with the ScriptEngine class: scriptengine.md
                - Using the graphical editor and the command line interface: asgui-asis.md
        - AddyScript's syntax:
            - Anatomy of a script: anatomy.md
            - Variables, operators and expressions: expressions.md
            - Controlling the program flow: flow-control.md
            - Special types: spec-types.md
            - Collections and objects: col-obj.md
            - Functions:
                - Inner functions: innerfunc.md
                - User-defined functions: userfunc.md
            - Object oriented programming:
                - Classes: classes.md
                - Inheritance and polymorphism: inheritance.md
                - Introspection: introspection.md
                - Interacting with .NET and the host platform: interop.md
            - Exceptions handling: exceptions.md
        - Extending AddyScript:
            - Extending the API: extapi.md
            - Extending the language syntax: extlang.md
            - Improving the scripting engine: improve.md
        - Licensing: license.md
        - About the author: aboutauth.md
        - Changes history: history.md

nav:
  - Home: README.md
  - Introduction:
    - Features: features.md
    - Tutorials:
      - Interpreting a script: interpret.md
      - Evaluating expressions: evaluate.md
      - More with the ScriptEngine class: scriptengine.md
      - Using the graphical editor and the command line interface: asgui-asis.md
  - AddyScript's syntax:
    - Anatomy of a script: anatomy.md
    - Variables, operators and expressions: expressions.md
    - Controlling the program flow: flow-control.md
    - Special types: spec-types.md
    - Collections and objects: col-obj.md
    - Functions:
      - Inner functions: innerfunc.md
      - User-defined functions: userfunc.md
    - Object oriented programming:
      - Classes: classes.md
      - Inheritance and polymorphism: inheritance.md
      - Introspection: introspection.md
      - Interacting with .NET and the host platform: interop.md
    - Exceptions handling: exceptions.md
    - AddyScript grammar: grammar.md
  - Extending AddyScript:
    - Extending the API: extapi.md
    - Extending the language syntax: extlang.md
    - Improving the scripting engine: improve.md
  - Licensing: license.md
  - About the author: aboutauth.md
  - Changes history: history.md
  - PDF version: assets/manual.pdf
