site_name: AddyScript Wiki
docs_dir: docs

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Light mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight

extra_css:
  - assets/manual.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      pygments_style: material
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - md_in_html

plugins:
  - search
  - to-pdf:
      output_path: assets/manual.pdf
      cover_logo: assets/cover.jpg
      cover_title: AddyScript Manual
      cover_subtitle: Developer Documentation (version 0.9.9.9, January 2026)
      author: Michel Mbem
      copyright: Â© Addy 2009-2026
      toc_title: Table of Contents
      debug_html: false
      exclude_pages:
        - grammar.*

nav:
  - Home: README.md
  - Introduction:
    - Features: features.md
    - Tutorials:
      - Interpreting a script: interpret.md
      - Evaluating expressions: evaluate.md
      - More with the ScriptEngine class: scriptengine.md
      - Using the graphical editor and the command line interface: asgui-asis.md
  - AddyScript's syntax:
    - Anatomy of a script: anatomy.md
    - Variables, operators and expressions: expressions.md
    - Controlling the program flow: flow-control.md
    - Special types: spec-types.md
    - Collections and objects: col-obj.md
    - Functions:
      - Inner functions: innerfunc.md
      - User-defined functions: userfunc.md
    - Object oriented programming:
      - Classes: classes.md
      - Inheritance and polymorphism: inheritance.md
      - Introspection: introspection.md
      - Interacting with .NET and the host platform: interop.md
    - Exceptions handling: exceptions.md
    - AddyScript grammar: grammar.md
  - Extending AddyScript:
    - Extending the API: extapi.md
    - Extending the language syntax: extlang.md
    - Improving the scripting engine: improve.md
  - Licensing: license.md
  - About the author: aboutauth.md
  - Changes history: history.md
  - PDF version: assets/manual.pdf
